### ISSUE TITLE
Lightswitch missing

### ISSUE THREAD

**Issue by arifje** [internetztube/craft-slug-equals-title#10] opened 2020-08-03 14:20 UTC
The lightswitch is missing in the CP and the slug doesn't get changes automatically when the title is edited anymore.

![Screenshot 2020-08-03 at 16 18 55](https://user-images.githubusercontent.com/1286410/89192718-3395d900-d5a5-11ea-9e3f-1fc9cb56c0e5.jpg)

Downgrading to 1.1.4 brings back the switch.

Craft CMS 3.4.28.1
Plugin version 1.2.0

**Comment by internetztube** [comment] 2020-08-03 16:21
Unfortunately, I cannot reproduce this issue. 
May you please send your `composer.json` and `composer.lock` to support@internetztube.net?

**Comment by internetztube** [comment] 2020-08-12 08:23
Do you still have this problem? @skoften

**Comment by arifje** [comment] 2020-08-12 08:25
Yes, I've just emailed the requested files

Edit: nevermind, I mixed this one up with another issue. I will check this plugin later today and let you know!

**Comment by internetztube** [comment] 2020-08-17 18:19
Ping. @skoften

**Comment by arifje** [comment] 2020-08-18 14:53
Updated to 1.2.0, lightswitch still gone. Downgraded to 1.1.4, lightswitch is back!

Craft CMS 3.4.28.1

**Comment by internetztube** [comment] 2020-08-18 16:01
Thanks for your bug report!

The bug should be fixed with 1.2.1. 
```
composer update internetztube/craft-slug-equals-title
```

**Closed as completed** 2020-08-18 16:00 UTC
